### ISSUE TITLE
Problem no have permission "ALL"

### ISSUE THREAD

**Issue by Benzitczo** [FriendsOfFlarum/user-directory#103]
Problem there no working "user all"
![image](https://github.com/FriendsOfFlarum/user-directory/assets/36309164/28d00ac5-7118-4c68-9579-0e6c7c2cb03e)

Translate: "Nanay from China! You don't have permission to do that."

![image](https://github.com/FriendsOfFlarum/user-directory/assets/36309164/485af0f2-9951-48a3-9429-07cbb574dfa9)

**Comment by clarkwinkelmann** [comment]
Make sure user also has "search user" permission, otherwise they can see the page but Flarum won't allow access to the list of users.

**Comment by Benzitczo** [comment]
> 

Yes, but without the account I can't see the list of users. But only the members and other more ranks if I can see it works well.

That's a bit of a problem :P
