### ISSUE TITLE
When I click refresh on the Member Directory page, I will get the following error

### ISSUE THREAD

**Issue by acolasialiuliu** [FriendsOfFlarum/user-directory#109]
When I click refresh on the Member Directory page, I will get the following error
![图片](https://github.com/FriendsOfFlarum/user-directory/assets/62091678/ee7aa7c9-dd55-45dd-a354-a04f2cb2c98c)
Deprecated: str_getcsv(): Passing null to parameter #1 ($string) of type string is deprecated in /www/wwwroot/bbs/vendor/flarum/core/src/Search/GambitManager.php on line 67

Fatal error: Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in /www/wwwroot/bbs/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:20 Stack trace: #0 /www/wwwroot/bbs/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(42): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent() #1 /www/wwwroot/bbs/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(21): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->assertNoPreviousOutput() #2 /www/wwwroot/bbs/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(75): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emit() #3 /www/wwwroot/bbs/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run() #4 /www/wwwroot/bbs/public/index.php(26): Flarum\Http\Server->listen() #5 {main} thrown in /www/wwwroot/bbs/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php on line 20

Here is my system environment
![图片](https://github.com/FriendsOfFlarum/user-directory/assets/62091678/6bff44cc-f23e-4ebc-a4ff-91485f5ff283)

**Comment by clarkwinkelmann** [comment]
The code that calls `str_getcsv` is in Flarum itself, not this extension.

In any case this is not an issue. You should hide deprecation warnings on your server and everything will work as expected. See `error_reporting` and `display_errors` config in your `php.ini` or PHP management panel.
