### ISSUE TITLE
Error if access to directory but not user list

### ISSUE THREAD

**Issue by clarkwinkelmann** [FriendsOfFlarum/user-directory#25]
If you have the "View user directory" permission but not the "View user list" permission you can access the page but it will result  in a "Something went wrong while trying to load the full version of this site. Try hard-refreshing this page to fix the error" error with message `TypeError: t is undefined` in the console

**Comment by Ralkage** [comment]
The first part of this issue doesn't seem to occur anymore but the second part still does; will definitely need to take a look at this issue when we start patching up some more.

![image](https://user-images.githubusercontent.com/2059356/113458427-32d96f00-93e0-11eb-8252-8a397edab939.png)

**Comment by dsevillamartin** [comment]
No longer an issue. Seems to be handled just fine.
