### ISSUE TITLE
Disable and abandon flagrow package on Packagist

### ISSUE THREAD

**Issue by clarkwinkelmann** [FriendsOfFlarum/user-directory#28]
https://packagist.org/packages/flagrow/user-directory

We need to:

- Mark package as abandoned in favor of fof/user-directory
- Disable picking up new tags

I don't have the access to do that, @luceos if you can take care of it, or add me as maintainer on the package so I can do it.

**Comment by clarkwinkelmann** [comment]
I'm not tagging any fof release until this is done, otherwise we might end up with tags in the wrong place.

**Comment by datitisev** [comment]
@clarkwinkelmann Feel free to tag, tags can be deleted later from Packagist.

**Comment by luceos** [comment]
Abandoned 👍
