### ISSUE TITLE
Ability to add user

### ISSUE THREAD

**Issue by gagarine** [FriendsOfFlarum/user-directory#31]
It's not possible to add a user in flarum from the admin. Neither is possible to invite a user (via email). In fact, if you close Sign up, their is no way to create a new user.

The ability for admin to add new user would be a great addition to this extinction.

**Comment by clarkwinkelmann** [comment]
Hello ! Thanks for the feedback.

I don't think it makes sense to bundle it with this extension as there appears to be no possible code reuse. Those would be two different features and as such would probably be best maintained separately.

I'm keeping this open for now while I discuss with the team where we want to store the feature suggestions.

**Comment by clarkwinkelmann** [comment]
The [Create User Modal](https://discuss.flarum.org/d/22608-create-user-modal) extension now adds this feature and provides integration with user directory.
