### ISSUE TITLE
Undefined variable: forum

### ISSUE THREAD

**Issue by anysite** [FriendsOfFlarum/user-directory#32]
Installing ^0.3.2 on core v0.1.0-beta.9
No previous installation of Flagrow package. 

Navigate to /users produce this error: 
```
compact(): Undefined variable: forum in FALARUM_BASE_DIR/vendor/fof/user-directory/src/Content/UserDirectory.php on line 72 
```

**Comment by clarkwinkelmann** [comment]
Thanks for the report ! Will fix ASAP.

Are you on PHP 7.3 by any chance ? Because I never encountered that error on my 7.1 and 7.2 dev setups.

**Comment by anysite** [comment]
Yes. it is PHP 7.3.7.

**Comment by datitisev** [comment]
I remember Flarum also having this issue for some people. The `forum` variable was never initialized, and yet used,  exactly like at https://github.com/FriendsOfFlarum/user-directory/blob/master/src/Content/UserDirectory.php#L73.

**Comment by clarkwinkelmann** [comment]
Additional note: it was only a PHP `Notice`, so it wouldn't be shown if warnings and notices were hidden as they should be in production :wink:
