### ISSUE TITLE
Feature request list layout and hide user

### ISSUE THREAD

**Issue by d-fankhauser** [FriendsOfFlarum/user-directory#45]
- allow the admin(s) to hide special users from the List
For example: i want to show all my admins, but there is one account that nobody should see in public. So you could hide him in that list?

- add an other listing
Maybe it should be possible to switch between the current list layout and an other one, where you have just a table with the basic informations like username, number of posts joined, last activity

**Comment by clarkwinkelmann** [comment]
This extension relies on Flarum own user listing endpoint, which unfortunately doesn't have such an option.

We can alter a Flarum endpoint, but then Flarum features relying on it, like mentions, would stop working correctly if not all users are returned.

Having a second API endpoint for the user directory wouldn't make much sense if you can just hit the main endpoint and find the user you're trying to hide from the other endpoint.

What would be the use case of hiding a user? Unless they never post, they would be discoverable one way or another.

Now if the idea is just to build a list with specified users, while not trying to prevent discovery of other users, that could be doable.

There's no plan to implement such a thing at this time though. We'd need to see how requested that feature is. Listing groups is a much-wanted feature which we will probably implement sooner, I believe it has its own GitHub issue.

**Comment by Ralkage** [comment]
Group filtering was added in https://github.com/FriendsOfFlarum/user-directory/pull/39 and hidden groups was added some time ago to Flarum core. Now, we won't be able to implement both feature requests, but for the first request, as long as you set the group to hidden, all groups that aren't part of the Admin group will not see the hidden group in the "Filter Groups" drop-down.

![image](https://user-images.githubusercontent.com/2059356/113459899-f4927e80-93e4-11eb-9e64-99e3f8f22503.png)

![image](https://user-images.githubusercontent.com/2059356/113459816-b301d380-93e4-11eb-8770-57bdd120b1f9.png)

It would be nice to see an extension or core feature down the line to hide users or even hide users that are part of hidden groups, but unfortunately that is not currently possible and not within the scope of this extension,

Nonetheless, thank you for submitting this feature request! We'll now proceed with closing this issue.
