### ISSUE TITLE
Compatibility with beta 14

### ISSUE THREAD

**Issue by HLFH** [FriendsOfFlarum/user-directory#48]
Hi,

It seems this extension is not compatible with [beta 14](https://discuss.flarum.org/d/5682-user-directory-by-friendsofflarum/183).
This is an issue to notify this may block the successful upgrade to beta 14 (https://discuss.flarum.org/d/25242-error-message-on-posting-in-beta-14/10).

**Comment by clarkwinkelmann** [comment]
Now compatible

**Comment by lostsnow** [comment]
The version on packagist is still 0.4.0, can someone update this?
