### ISSUE TITLE
Feature Request: Search

### ISSUE THREAD

**Issue by codemotion** [FriendsOfFlarum/user-directory#58]
This great plugin is lack of search field.

Please make search field above the list (right to filtering).

**Comment by clarkwinkelmann** [comment]
There is already partial search support.

In Flarum you can natively search for users using the global search bar.

When user directory is enabled, a link is added in the search result dropdown to display the user directory page with filtered results. You can even share the link which has a `?q=` parameter.

There's a separate related issue about filters #10 

I have a design ready for a search+filter field for the extension, but it's currently only in the beta 13 version https://github.com/FriendsOfFlarum/user-directory/tree/cw-search-field
