### ISSUE TITLE
Unchecking "Add link on homepage for users able to see the directory" causes the "canSeeUserDirectoryLink" attribute to be false

### ISSUE THREAD

**Issue by rafaucau** [FriendsOfFlarum/user-directory#63]
I unchecked the `Add link on homepage for users able to see the directory` option to add a link to the User Directory elsewhere.
```jsx
{app.forum.attribute('canSeeUserDirectoryLink') && (
  <LinkButton icon="far fa-address-book" href={app.route('fof_user_directory')}>
    {app.translator.trans('fof-user-directory.forum.page.nav')}
  </LinkButton>
)}
```
And it wouldn't work. It turned out that after unchecking this option, the `canSeeUserDirectoryLink` attribute is false.

![image](https://user-images.githubusercontent.com/25438601/110150165-34167c80-7ddf-11eb-9546-c56cb00f5cbc.png)
![image](https://user-images.githubusercontent.com/25438601/110150261-55776880-7ddf-11eb-9a23-ad564bd40cfd.png)
This option should be independent of permissions.

**Comment by clarkwinkelmann** [comment]
`canSeeUserDirectoryLink` is `true` if you have `fof.user-directory.view` permission AND the `fof-user-directory-link` setting is turned on. It's defined here https://github.com/FriendsOfFlarum/user-directory/blob/master/src/PermissionBasedForumSettings.php#L25

What you're describing seems to be the correct behavior. You disable the link setting, the link boolean goes to false (?)

The whole purpose of this attribute is to control whether the link will be inserted.

If you need to know whether the user has access to the user directly, you could expose a new attribute that is only based on whether you have `fof.user-directory.view` permission. It could be called just `canSeeUserDirectory`.

**Comment by Ralkage** [comment]
Based on @clarkwinkelmann's recent comment, it's safe to say that this is par of the intended functionality of this extension. Clark also added a tidbit of how you can get around this. In hindsight, we will proceed with closing this issue.
