### ISSUE TITLE
Sidebar link visible when on user directory page

### ISSUE THREAD

**Issue by robinheidrich** [FriendsOfFlarum/user-directory#68]
The sidebar link is disabled in the settings, but is still displayed only when you go to the user directory page.

I'm using version 0.6.2.

**Comment by clarkwinkelmann** [comment]
That's intended behavior. It provides context about where the user is.

Also on mobile it becomes the name in the header in the side navigation switcher.

**Comment by imorland** [comment]
Closing as this is intended behaviour
