### ISSUE TITLE
How to edit this button in user profile

### ISSUE THREAD

**Issue by rgcz** [FriendsOfFlarum/user-directory#72]
Hi, can i ask what put in css when i want edit this button in user card profile ? This is card inside discussion when open user profile.
I need recolor this in to white color. Thanks
![1121](https://user-images.githubusercontent.com/85392728/120889871-8b570380-c5ff-11eb-9dd4-f4577ba4687a.jpg)

**Comment by clarkwinkelmann** [comment]
The card on the discussion page is not managed by User Directory extension. That component is called the UserCard is we re-use it on the user list page.

The dropdown used in the UserCard has class `.UserCard-controls`. The 3-dot button is `.UserCard-controls .Dropdown-toggle`.

To customize the style everywhere *but* User Directory, you could use `.UserCard:not(.UserCard--directory)` or use other classes that are unique to the page the card is rendered on.

If there's actually a problem with User Directory please share more details and I'll re-open this :slightly_smiling_face:
