### ISSUE TITLE
The Flarum search focuses by default on searching for users.

### ISSUE THREAD

**Issue by rafaucau** [FriendsOfFlarum/user-directory#76]
## Bug Report

**Current Behavior**
When I want to search for something quickly on the forum, I type in a phrase and press enter. Instead of getting the discussions I am looking for, I get the user directory. This is because the Flarum global search engine focuses on the user search option instead of the discussion.

**Steps to Reproduce**
1. enable fof/user-directory
2. try to search for something on the forums

**Expected Behavior**
The search engine should search for discussions instead of users by default.
If this is not a bug and is intentional, then there should be an option to change the default search.

**Screenshots**
![image](https://user-images.githubusercontent.com/25438601/123456984-c12a4f00-d5e3-11eb-96d3-500dca747d70.png)

**Environment**
- Flarum version: 1.0.3
- Extension version: 1.0.2

**Comment by dsevillamartin** [comment]
I believe this has been fixed at some point since I cannot reproduce this.
