### ISSUE TITLE
Users without directory permissions see 403s during post drafting due to @mentions

### ISSUE THREAD

**Issue by likuilin** [FriendsOfFlarum/user-directory#80]
## Bug Report

**Current Behavior**
Users without directory permissions see 403s during post drafting due to @mentions

**Steps to Reproduce**
1. Have Mentions and User Directory installed
2. Log in as a user without the "View user directory" permission
3. Compose a post or reply and type "@asdf" and then space
4. See 403s and "You do not have permission to do that." red popup in corner

**Expected Behavior**
No 403s happen during regular use of the web UI.

**Screenshots**
N/A

**Environment**
- Flarum version: 7.4.19
- Extension version: 1.0.2
- Website URL: Not public
- Webserver: nginx, flarum in docker
- Hosting environment: docker in EC2
- PHP version: 7.4.19
- Browser: Chrome 73

```
Output of "php flarum info", run this in terminal in your Flarum directory.
Flarum core 1.0.0
PHP version: 7.4.19
Loaded extensions: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, ctype, curl, dom, fileinfo, gd, gmp, iconv, intl, json, mbstring, openssl, PDO, standard, SimpleXML, sodium, tokenizer, xml, xmlwriter, zip, exif, mysqlnd, Phar, pdo_mysql, uuid, Zend OPcache
+----------------------+------------+--------+
| Flarum Extensions    |            |        |
+----------------------+------------+--------+
| ID                   | Version    | Commit |
+----------------------+------------+--------+
| flarum-markdown      | v1.0.0     |        |
| fof-impersonate      | 1.0.0      |        |
| flarum-suspend       | v1.0.0     |        |
| flarum-tags          | v1.0.0     |        |
| askvortsov-rich-text | v2.1.0     |        |
| [redacted]           | dev-master |        |
| fof-moderator-notes  | 1.0.0      |        |
| fof-upload           | 1.0.2      |        |
| flarum-nicknames     | v1.0.0     |        |
| flarum-subscriptions | v1.0.0     |        |
| flarum-sticky        | v1.0.0     |        |
| flarum-statistics    | v1.0.0     |        |
| flarum-mentions      | v1.0.0     |        |
| flarum-lock          | v1.0.0     |        |
| flarum-likes         | v1.0.0     |        |
| flarum-lang-english  | v1.0.0     |        |
| flarum-emoji         | v1.0.0     |        |
| flarum-bbcode        | v1.0.0     |        |
| fof-user-directory   | 1.0.2      |        |
| flarum-flags         | v1.0.0     |        |
| fof-webhooks         | 1.0.4      |        |
+----------------------+------------+--------+
Base URL: [redacted]
Installation path: /opt/flarum
Debug mode: off
```

**Possible solution(s)**

Disable the dropdown for searching users by name when typing @ in the composition when the user doesn't have the directory permission. Alternatively, have a different permission for searching users by name and outright enumeration of users.

**Comment by clarkwinkelmann** [comment]
I think this is referring to this core issue https://github.com/flarum/core/issues/3070

Having access to the user directory page doesn't matter here, it's whether the user is allowed to search users on the forum, which is a native Flarum permission.
