### ISSUE TITLE
Export option 

### ISSUE THREAD

**Issue by orschiro** [FriendsOfFlarum/user-directory#94]
Hi all,

Would it be possible to add an export option so that one could export the user list zo common formats such as CSV?

Thanks ahead!

**Comment by clarkwinkelmann** [comment]
I'd say this is out of scope of this extension. There's no overlap in implementation, except that an export extension could add its button on the directory page, which is already possible using the javascript exports of the extension.

That would be material for a new extension, but there's currently no plan for FriendsOfFlarum to create new extensions.

**Comment by orschiro** [comment]
Thanks Clark, appreciate your clear position on this.
